name: macOS

on:
  push:
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  test:
    runs-on: macos-latest
    name: CMake v3.${{ matrix.cmake_version }}
    strategy:
      fail-fast: false
      matrix:
        cmake_version: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: ⬇️ Setup CMake
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: ~3.${{ matrix.cmake_version }}
          ninjaVersion: ^1
      - name: CMake --help
        run: cmake --help
      
      - name: ⚙️ run-cmake (configure)
        uses: ./
        id: configure
        with:
          mode: configure
          install_prefix: './MyInstallPrefix'
          variables: |
            AFTER_CACHE_BOOL:BOOL=TRUE
            AFTER_CACHE_STRING:STRING="MyString"
          configure_warnings: deprecated
          configure_warnings_as_errors: ''
          list_cache_variables: 'advanced_help'
          graphviz: './graph.dot'
          log_level: 'TRACE'
          log_context: true

      - name: 🛠️ run-cmake (build)
        uses: ./
        id: build
        with:
          mode: build
          clean_first: true
          build_verbose: true

      - name: 📥 run-cmake (install)
        uses: ./
        id: install
        with:
          mode: install
          install_verbose: false
        
